In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import seaborn as sns

In [166]:
REWARD_NONTERMINAL = -1
REWARD_TERMINAL = 10
REWARD_CLIFF = -100

class Environment:

    def __init__(self, nr_columns, nr_rows, nr_actions=4, init_qa_values=0):
        self.world = np.zeros((nr_rows + 1, nr_columns))
        self.nr_columns = nr_columns
        self.nr_rows = nr_rows
        self.nr_actions = nr_actions
        
    def set_world_rewards(self):
        pass

class CliffEnvironment(Environment):
    
    def __init__(self, nr_columns, nr_rows, nr_actions=4, init_qa_values=0):
        super().__init__(nr_columns, nr_rows)
        self.set_world_rewards()
        
    def set_world_rewards(self):
        self.world[:, :] = REWARD_NONTERMINAL
        self.world[self.nr_rows:, 1:self.nr_columns - 1] = REWARD_CLIFF
        self.world[self.nr_rows, self.nr_columns - 1] = REWARD_TERMINAL

In [3]:
class Agent:
    def __init__(self, env, init_position=(0,0)):
        self.curr_state = init_position
        self.env = env
        self.q_table = np.zeros((env.nr_columns, env.nr_rows + 1, env.nr_actions))
        
    def run(self):
        pass
    
    def get_next_action(self):
        # get_next_action: get the next step according to epsilon-greedy algorithm (next-step)
        actions = self.q_table[self.curr_state]
        pass
    
    def get_next_state(self, action):
            # get_next_state: get next state according to the environment, which also gets the reward
        
        pass
    
    def update_q_table(self, next_state, next_best_action):
            # update_q_table: add to current q_entry the reward, and the best action next action from the next state
        
        pass
        
class QLearner(Agent):
    def __init__(self, env, nr_episodes, init_position=(0,0)):
        super().__init__(env, init_position)
        self.nr_episodes = nr_episodes
        
    def run(self):
        for i in range(self.nr_episodes):
            terminated = False
            
            while not Terminate:
#             While in episode:
                next_action = self.get_next_action()
                next_state = self.get_next_state()
                next_best_action = self.get_best_action(next_state)
                self.update_q_table(next_state, next_best_action)

    def get_best_action(self, state):
        return np.argmax(self.env.world[state])
        
    
class SarsaLearner(Agent):
    def __init__(self, env, nr_episodes, init_position=(0,0)):
        super().__init__(env, init_position)
        self.nr_episodes = nr_episodes
        
    def run(self):
        for i in range(self.nr_episodes):
            pass
            

In [164]:
###
# Main Run - Initialization
###
NR_COLUMNS = 5

# Excluding the cliff
NR_ROWS = 3

cliffWorld = CliffEnvironment(NR_COLUMNS, NR_ROWS)
agent = QLearner(cliffWorld, (0, NR_ROWS))

In [165]:
print(agent.q_table)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
